from manim import *
import numpy as np
import math

def length(A,B):
    x=B[0]-A[0]
    y=B[1]-A[1]
    return math.sqrt(x**2+y**2)


sqrt_3=math.sqrt(3)
sqrt_7=math.sqrt(7)
theta=math.atan(3*sqrt_3)/3
cos_theta=math.cos(theta)
sin_theta=math.sin(theta)

alpha=2*PI/7
cos_alpha=math.cos(alpha)
cos_2alpha=math.cos(2*alpha)
cos_3alpha=math.cos(3*alpha)
sin_alpha=math.sin(alpha)
sin_2alpha=math.sin(2*alpha)
sin_3alpha=math.sin(3*alpha)
        
O=np.array([0,0,0])
A1=np.array([1,0,0])
A2=np.array([2,0,0])
A3=np.array([3,0,0])
B=np.array([3/2,3*sqrt_3/2,0])
C=np.array([1/2,3*sqrt_3/2,0])
D=np.array([-sqrt_7,0,0])
E=np.array([sqrt_7,0,0])
F=np.array([-sqrt_7*cos_theta,sqrt_7*sin_theta,0])
G1=np.array([sqrt_7*cos_theta,sqrt_7*sin_theta,0])
G2=np.array([sqrt_7*cos_theta,-sqrt_7*sin_theta,0])
H=np.array([sqrt_7*cos_theta,0,0])
I=np.array([sqrt_7*cos_theta-1,0,0])
J1=np.array([3*cos_alpha,3*sin_alpha,0])
J2=np.array([3*cos_alpha,-3*sin_alpha,0])
K1=np.array([3*cos_2alpha,3*sin_2alpha,0])
K2=np.array([3*cos_2alpha,-3*sin_2alpha,0])
L1=np.array([3*cos_3alpha,3*sin_3alpha,0])
L2=np.array([3*cos_3alpha,-3*sin_3alpha,0])

dot_O=Dot(O)
dot_A1=Dot(A1)
dot_A2=Dot(A2)
dot_A3=Dot(A3)
dot_B=Dot(B)
dot_C=Dot(C)
dot_D=Dot(D)
dot_E=Dot(E)
dot_F=Dot(F)
dot_G1=Dot(G1)
dot_G2=Dot(G2)
dot_H=Dot(H)
dot_I=Dot(I)
dot_J1=Dot(J1)
dot_J2=Dot(J2)
dot_K1=Dot(K1)
dot_K2=Dot(K2)
dot_L1=Dot(L1)
dot_L2=Dot(L2)

line=Line(np.array([-6,0,0]), np.array([6,0,0]))
parallel=Line(np.array([-6,3*sqrt_3/2,0]),np.array([6,3*sqrt_3/2,0]))


circle_rad_1=Circle(radius=1,color='#0080ff')
circle_rad_3=Circle(radius=3,color='#0080ff')
circle=Circle(radius=3,color='#ffffff')
circle_OC=Circle(radius=sqrt_7,color='#ffffff').move_to(O)

class part1(Scene):
    def construct(self):
        colored_dot_O=Dot(O)
        colored_dot_A1=Dot(A1)
        colored_dot_A2=Dot(A2)
        colored_dot_A3=Dot(A3)

        arc_A1=Arc(radius=1,start_angle=PI/24,angle=-PI/12,arc_center=A1).set_z_index(1)
        arc_A2=Arc(radius=1,start_angle=PI/24,angle=-PI/12,arc_center=A2).set_z_index(1)
        arc_A3=Arc(radius=3,start_angle=31*PI/48,angle=PI/24,arc_center=A3).set_z_index(1)
        self.play(Create(line))
        self.play(FadeIn(dot_O,dot_A1))
        colored_dot_O.set_color('#ff0080')
        colored_dot_A1.set_color('#00ffff')
        circle_rad_1.move_to(A1)
        self.play(FadeIn(colored_dot_O,colored_dot_A1))
        self.play(FadeIn(circle_rad_1))
        self.play(Create(arc_A1))
        self.play(FadeOut(circle_rad_1,colored_dot_O,colored_dot_A1))
        self.play(FadeIn(dot_A2))
        self.play(FadeOut(arc_A1))

        colored_dot_A1.set_color('#ff0080')
        colored_dot_A2.set_color('#00ffff')
        circle_rad_1.move_to(A2)
        self.play(FadeIn(colored_dot_A1,colored_dot_A2))
        self.play(FadeIn(circle_rad_1))
        self.play(Create(arc_A2))
        self.play(FadeOut(circle_rad_1,colored_dot_A1,colored_dot_A2))
        self.play(FadeIn(dot_A3))
        self.play(FadeOut(arc_A2,dot_A2))

        colored_dot_O.set_color('#00ffff')
        colored_dot_A3.set_color('#ff0080')
        circle_rad_3.move_to(A3)
        self.play(FadeIn(colored_dot_O,colored_dot_A3))
        self.play(Create(circle))
        self.play(FadeOut(colored_dot_O,colored_dot_A3))
        colored_dot_O.set_color('#ff0080')
        colored_dot_A3.set_color('#00ffff')
        circle_rad_3.move_to(A3)
        self.play(FadeIn(colored_dot_O,colored_dot_A3))
        self.play(FadeIn(circle_rad_3))
        self.play(Create(arc_A3))
        self.play(FadeOut(circle_rad_3,colored_dot_O,colored_dot_A3))
        self.play(FadeIn(dot_B))
        self.play(FadeOut(arc_A3))

class part2(Scene):
    def construct(self):
        colored_dot_O=Dot(O).set_color('#ff0080')
        colored_dot_B=Dot(B).set_color('#00ffff')
        colored_dot_A1=Dot(A1).set_color('#ff0080')
        self.add(line,dot_O,dot_A1,dot_A3,circle,dot_B)
        
        ray_OB=Line(O,np.array([2.25,2.25*sqrt_3,0]))
        colored_dot_B.set_color('#ff0080')
        self.play(FadeIn(colored_dot_O,colored_dot_B))
        self.play(Create(ray_OB))
        self.play(FadeOut(colored_dot_O,colored_dot_B))

        circle_rad_1.move_to(B)
        circle_B=Circle(radius=1,color='#ffffff').move_to(B)
        B1=np.array([2,2*sqrt_3,0])
        dot_B1=Dot(B1)
        colored_dot_B1=Dot(B1).set_color('#00ffff')
        seg_OA1=Line(O,A1,color='#ff0080')
        self.play(FadeIn(colored_dot_O,colored_dot_A1))
        self.play(FadeIn(seg_OA1))
        self.play(FadeOut(colored_dot_O,colored_dot_A1),seg_OA1.animate.shift(B-O),FadeIn(colored_dot_B))
        self.play(Create(circle_B))
        self.play(FadeOut(colored_dot_B))
        self.play(FadeIn(dot_B1))
        
        
        circle_rad_1.move_to(B1)
        arc_B1=Arc(radius=1,start_angle=-3*PI/8,angle=PI/12,arc_center=B1).set_z_index(1)
        self.play(seg_OA1.animate.shift(B1-B),FadeIn(colored_dot_B1))
        colored_dot_B.set_color('#ff0080')
        self.play(FadeIn(circle_rad_1))
        self.play(Create(arc_B1))
        B2=np.array([5/2,3*sqrt_3/2,0])
        dot_B2=Dot(B2)
        colored_dot_B2=Dot(B2).set_color('#ff0080')
        self.play(FadeOut(colored_dot_B1,circle_rad_1,seg_OA1))
        self.play(FadeIn(dot_B2))
        self.play(FadeOut(arc_B1))
        self.play(FadeIn(colored_dot_B,colored_dot_B2))
        self.play(Create(parallel))
        self.play(FadeOut(colored_dot_B,colored_dot_B2))
        self.play(FadeOut(dot_B1,dot_B2,circle_B,ray_OB))
        self.wait()

class part3(Scene):
    def construct(self):
        self.add(line,dot_O,dot_A1,dot_A3,circle,dot_B,parallel)

        circle_rad_1.move_to(O)
        colored_dot_O=Dot(O).set_color('#00ffff')
        colored_dot_A1=Dot(A1).set_color('#ff0080')
        arc_O_1=Arc(radius=1,start_angle=3*PI/8,angle=-PI/12,arc_center=O).set_z_index(1)
        arc_O_2=Arc(radius=1,start_angle=-3*PI/8,angle=PI/12,arc_center=O).set_z_index(1)
        self.play(FadeIn(colored_dot_O,colored_dot_A1))
        self.play(FadeIn(circle_rad_1))
        self.play(Create(arc_O_1),Create(arc_O_2))
        self.play(FadeOut(colored_dot_O,colored_dot_A1,circle_rad_1))

        circle_rad_1.move_to(A1)
        colored_dot_O=Dot(O).set_color('#ff0080')
        colored_dot_A1=Dot(A1).set_color('#00ffff')
        arc_A1_1=Arc(radius=1,start_angle=5*PI/8,angle=PI/12,arc_center=A1).set_z_index(1)
        arc_A1_2=Arc(radius=1,start_angle=-5*PI/8,angle=-PI/12,arc_center=A1).set_z_index(1)
        self.play(FadeIn(colored_dot_O,colored_dot_A1))
        self.play(FadeIn(circle_rad_1))
        self.play(Create(arc_A1_1),Create(arc_A1_2))
        self.play(FadeOut(colored_dot_O,colored_dot_A1,circle_rad_1))
        
        perp1=np.array([1/2,sqrt_3/2,0])
        perp2=np.array([1/2,-sqrt_3/2,0])
        dot_perp1=Dot(perp1)
        dot_perp2=Dot(perp2)
        colored_dot_perp1=Dot(perp1).set_color('#ff0080')
        colored_dot_perp2=Dot(perp2).set_color('#ff0080')
        perp=Line(np.array([1/2,7/2,0]),np.array([1/2,-7/2,0]))
        self.play(FadeIn(dot_perp1,dot_perp2))
        self.play(FadeOut(arc_A1_1,arc_A1_2,arc_O_1,arc_O_2))
        
        self.play(FadeIn(colored_dot_perp1,colored_dot_perp2))
        self.play(Create(perp))
        self.play(FadeOut(colored_dot_perp1,colored_dot_perp2))
        self.play(FadeOut(dot_perp1,dot_perp2))
        self.play(FadeIn(dot_C))
        self.play(FadeOut(perp,dot_B,parallel))

        colored_dot_O=Dot(O).set_color('#00ffff')
        colored_dot_C=Dot(C).set_color('#ff0080')
        self.play(FadeIn(colored_dot_O,colored_dot_C))
        self.play(Create(circle_OC))
        self.play(FadeOut(colored_dot_O,colored_dot_C))
        self.play(FadeIn(dot_D,dot_E))

class part4(Scene):
    def construct(self):
        self.add(line,dot_O,dot_A1,dot_A3,circle,circle_OC,dot_C,dot_D,dot_E)
        ruler=Line(np.array([-6,-3.25,0]),np.array([6,-3.25,0]),color='#ffff00').set_z_index(1)
        compass_0=np.array([-16/3,3.25,0])
        compass_1=np.array([-16/3,-3.25,0])
        compass_2=np.array([-2*sqrt_7*cos_theta,0,0])
        compass_center=Dot(compass_0,color='#00ff00').set_z_index(2)
        compass_circum=Arc(radius=sqrt_7,start_angle=PI/48,angle=-PI/24,arc_center=compass_0,color='#00ff00').set_z_index(2)
        seg_OE=Line(O,E,color='#ff0080')

        colored_dot_O=Dot(O).set_color('#ff0080')
        colored_dot_C=Dot(C).set_color('#ff0080')
        colored_dot_E=Dot(E).set_color('#ff0080')
        
        self.play(FadeIn(colored_dot_O,colored_dot_E))
        self.play(FadeIn(seg_OE))
        self.play(FadeOut(colored_dot_O,colored_dot_E),seg_OE.animate.shift(compass_0))
        self.play(FadeIn(compass_center,compass_circum))
        
        self.play(FadeOut(seg_OE))
        self.play(FadeIn(ruler))
        self.play(compass_center.animate.shift(np.array([0,-6.5,0])),compass_circum.animate.shift(np.array([0,-6.5,0])))

        colored_circle_OC=Circle(radius=sqrt_7,color='#ff0080')
        colored_line=Line(np.array([-6,0,0]), np.array([6,0,0]),color='#ff0080')

        shift_vec=compass_2-compass_1
        self.play(FadeIn(colored_circle_OC,colored_line,colored_dot_C))
        self.play(ruler.animate.rotate(theta,about_point=compass_1).shift(shift_vec),
                    compass_center.animate.rotate(theta,about_point=compass_1).shift(shift_vec),
                    compass_circum.animate.rotate(theta,about_point=compass_1).shift(shift_vec))
        self.play(FadeOut(colored_circle_OC,colored_line,colored_dot_C))

        self.play(FadeOut(ruler))
        arc=Arc(radius=sqrt_7,start_angle=theta+PI/24,angle=-PI/12,arc_center=compass_2)
        arc.set_z_index(3)
        self.play(Create(arc))
        self.play(FadeOut(compass_center,compass_circum))
        self.play(FadeIn(dot_F))
        self.play(FadeOut(arc))

        length_DF=length(D,F)
        colored_dot_D=Dot(D).set_color('#ff0080')
        colored_dot_F=Dot(F).set_color('#ff0080')
        colored_dot_E.set_color('#00ffff')
        seg_DF=Line(D,F,color='#ff0080')
        circle_DF=Circle(radius=length_DF,color='#0080ff').move_to(E)

        self.play(FadeIn(colored_dot_D,colored_dot_F))
        self.play(FadeIn(seg_DF))
        self.play(FadeOut(colored_dot_D,colored_dot_F),FadeIn(colored_dot_E),seg_DF.animate.shift(2*E))
        self.play(FadeIn(circle_DF))
        arc_E1=Arc(radius=length_DF,start_angle=13*PI/24+theta/2,angle=-PI/12,arc_center=E).set_z_index(1)
        arc_E2=Arc(radius=length_DF,start_angle=-13*PI/24-theta/2,angle=PI/12,arc_center=E).set_z_index(1)
        self.play(Create(arc_E1),Create(arc_E2))
        self.play(FadeOut(colored_dot_E,seg_DF,circle_DF))
        self.play(FadeIn(dot_G1,dot_G2))
        self.play(FadeOut(arc_E1,arc_E2))

        colored_dot_G1=Dot(G1).set_color('#ff0080')
        colored_dot_G2=Dot(G2).set_color('#ff0080')
        seg_G=Line(G1,G2)
        self.play(FadeIn(colored_dot_G1,colored_dot_G2))
        self.play(Create(seg_G))
        self.play(FadeOut(colored_dot_G1,colored_dot_G2))
        self.play(FadeIn(dot_H))
        self.play(FadeOut(dot_C,dot_D,dot_E,dot_F,dot_G1,dot_G2,circle_OC,seg_G))

class part5(Scene):
    def construct(self):
        self.add(line,circle,dot_O,dot_A1,dot_A3,dot_H)
        circle_rad_1.move_to(H)
        seg_OA1=Line(O,A1,color='#ff0080')
        colored_dot_O=Dot(O).set_color('#ff0080')
        colored_dot_A1=Dot(A1).set_color('#ff0080')
        colored_dot_H=Dot(H).set_color('#00ffff')
        self.play(FadeIn(colored_dot_O,colored_dot_A1))
        self.play(FadeIn(seg_OA1))
        self.play(FadeOut(colored_dot_O,colored_dot_A1),FadeIn(colored_dot_H),seg_OA1.animate.shift(H))
        self.play(FadeIn(circle_rad_1))
        arc_H=Arc(radius=1,start_angle=7*PI/12,angle=5*PI/6,arc_center=H).set_z_index(1)
        self.play(Create(arc_H))
        self.play(FadeOut(colored_dot_H,seg_OA1,circle_rad_1))
        self.play(FadeIn(dot_I))
        self.play(FadeOut(dot_A1))
        
        colored_dot_H.set_color('#ff0080')
        colored_dot_I=Dot(I).set_color('#00ffff').set_z_index(2)
        arc_I=Arc(radius=1,start_angle=5*PI/12,angle=-5*PI/6,arc_center=I).set_z_index(3)
        perp1=np.array([3*math.cos(alpha),sqrt_3/2,0])
        perp2=np.array([3*math.cos(alpha),-sqrt_3/2,0])
        dot_perp1=Dot(perp1)
        dot_perp2=Dot(perp2)
        colored_dot_perp1=Dot(perp1).set_color('#ff0080')
        colored_dot_perp2=Dot(perp2).set_color('#ff0080')
        perp=Line(np.array([3*math.cos(alpha),7/2,0]),np.array([3*math.cos(alpha),-7/2,0]))
        circle_rad_1.move_to(I)
        self.play(FadeIn(colored_dot_H,colored_dot_I))
        circle_rad_1.set_z_index(2)
        self.play(FadeIn(circle_rad_1))
        self.play(Create(arc_I))
        self.play(FadeOut(colored_dot_H,colored_dot_I,circle_rad_1))
        self.play(FadeIn(dot_perp1,dot_perp2))
        self.play(FadeOut(arc_H,arc_I))
        
        self.play(FadeIn(colored_dot_perp1,colored_dot_perp2))
        self.play(Create(perp))
        self.play(FadeOut(colored_dot_perp1,colored_dot_perp2))
        self.play(FadeOut(dot_perp1,dot_perp2))

        self.play(FadeIn(dot_J1,dot_J2))
        self.play(FadeOut(dot_O,line,perp,dot_H,dot_I))

        side_length=length(J1,A3)
        circle_side=Circle(radius=side_length,color='#0080ff').move_to(J1)
        arc_J1=Arc(radius=side_length,start_angle=13*PI/14-PI/48,angle=PI/24,arc_center=J1).set_z_index(1)
        arc_J2=Arc(radius=side_length,start_angle=-13*PI/14+PI/48,angle=-PI/24,arc_center=J2).set_z_index(1)
        arc_K1=Arc(radius=side_length,start_angle=-11*PI/14-PI/48,angle=PI/24,arc_center=K1).set_z_index(1)
        arc_K2=Arc(radius=side_length,start_angle=11*PI/14+PI/48,angle=-PI/24,arc_center=K2).set_z_index(1)
        colored_dot_A3=Dot(A3).set_color('#ff0080')
        colored_dot_J1=Dot(J1).set_color('#00ffff')
        colored_dot_J2=Dot(J2).set_color('#00ffff')
        colored_dot_K1=Dot(K1).set_color('#00ffff')
        colored_dot_K2=Dot(K2).set_color('#00ffff')
        colored_dot_L1=Dot(L1).set_color('#ff0080')
        colored_dot_L2=Dot(L2).set_color('#ff0080')

        self.play(FadeIn(colored_dot_A3,colored_dot_J1))
        self.play(FadeIn(circle_side))
        self.play(Create(arc_J1))
        self.play(FadeOut(circle_side,colored_dot_A3,colored_dot_J1))
        self.play(FadeIn(dot_K1))
        self.play(FadeOut(arc_J1))

        circle_side.move_to(K1)
        colored_dot_J1=Dot(J1).set_color('#ff0080')
        self.play(FadeIn(colored_dot_K1,colored_dot_J1))
        self.play(FadeIn(circle_side))
        self.play(Create(arc_K1))
        self.play(FadeOut(circle_side,colored_dot_K1,colored_dot_J1))
        self.play(FadeIn(dot_L1))
        self.play(FadeOut(arc_K1))

        circle_side.move_to(J2)
        self.play(FadeIn(colored_dot_A3,colored_dot_J2))
        self.play(FadeIn(circle_side))
        self.play(Create(arc_J2))
        self.play(FadeOut(circle_side,colored_dot_A3,colored_dot_J2))
        self.play(FadeIn(dot_K2))
        self.play(FadeOut(arc_J2))

        circle_side.move_to(K2)
        colored_dot_J2=Dot(J2).set_color('#ff0080')
        self.play(FadeIn(colored_dot_K2,colored_dot_J2))
        self.play(FadeIn(circle_side))
        self.play(Create(arc_K2))
        self.play(FadeOut(circle_side,colored_dot_K2,colored_dot_J2))
        self.play(FadeIn(dot_L2))
        self.play(FadeOut(arc_K2))

        seg_A3J1=Line(A3,J1)
        seg_A3J2=Line(A3,J2)
        seg_J1K1=Line(J1,K1)
        seg_J2K2=Line(J2,K2)
        seg_K1L1=Line(K1,L1)
        seg_K2L2=Line(K2,L2)
        seg_L1L2=Line(L1,L2)
        colored_dot_K1.set_color('#ff0080')
        colored_dot_K2.set_color('#ff0080')

        self.play(FadeIn(colored_dot_A3,colored_dot_J1,colored_dot_J2,colored_dot_K1,colored_dot_K2,colored_dot_L1,colored_dot_L2))
        self.play(Create(seg_A3J1),Create(seg_A3J2),Create(seg_J1K1),Create(seg_J2K2),Create(seg_K1L1),Create(seg_K2L2),Create(seg_L1L2))
        self.play(FadeOut(colored_dot_A3,colored_dot_J1,colored_dot_J2,colored_dot_K1,colored_dot_K2,colored_dot_L1,colored_dot_L2))
        self.play(FadeOut(dot_A3,dot_J1,dot_J2,dot_K1,dot_K2,dot_L1,dot_L2,circle))

        heptagon_edges = VGroup(seg_A3J1,seg_A3J2,seg_J1K1,seg_J2K2,seg_K1L1,seg_K2L2,seg_L1L2)
        heptagon = Polygon(A3,J1,K1,L1,L2,K2,J2,fill_color="#ff0080",fill_opacity=1,stroke_width=0)
        self.play(FadeIn(heptagon),FadeOut(heptagon_edges))
        self.add(heptagon)
        
        self.wait()
        self.play(Rotate(heptagon, angle=2*PI, run_time=4, rate_func=linear))
        self.wait()
        self.play(FadeOut(heptagon))
